# Generated by Django 4.1.2 on 2022-11-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='*제목은 최대 100자 이내', max_length=200, verbose_name='글 제목')),
                ('author', models.CharField(max_length=100, verbose_name='글쓴이')),
                ('content', models.TextField(verbose_name='글 내용')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='등록(수정)일')),
            ],
        ),
    ]
